version: "3.1"

services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    env_file:
      - ./.env
    environment:
      - PORT=80
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    # ports:
    #   - '3307:3307'
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}